src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\MOP\Group;
use AppBundle\Util\StringsFunctions;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Serializable;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * User
 *
 * @ORM\Table(name="usuarios")
 * @ORM\Entity()
 */
class User implements AdvancedUserInterface, EquatableInterface, Serializable
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string")
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\Email(
     *        message="Invalid email '{{ value }}'",
     *        checkMX = true
     * )
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\Length(min=6, minMessage="Password too short")
     * @Assert\NotBlank(message="Password is required")
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $salt;

    /**
     * @var bool
     *
     * @ORM\Column(name="activo", type="boolean", nullable=true)
     */
    private $active;

    /**
     * @var string
     *
     * @ORM\Column(name="logo", type="string", nullable=true)
     */
    private $avatar;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $session;

    /**
     * @Assert\Image(maxSize = "3500k")
     */
    private $uploadedFile;

    /**
     * @var DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\Type(type="\DateTime")
     */
    private $lastAccess;

    /**
     * @var Role
     *
     * @ORM\ManyToOne(targetEntity="Role")
     * @Assert\NotNull()
     */
    private $role;

    /**
     * @var string|null
     *
     * @ORM\Column(name="direccion", type="text", length=65535, nullable=true)
     */
    private $direccion;

    /**
     * @var string
     *
     * @ORM\Column(name="calle", type="string", length=200, nullable=true)
     */
    private $calle;

    /**
     * @var string
     *
     * @ORM\Column(name="poblacion", type="string", length=100, nullable=true)
     */
    private $poblacion;

    /**
     * @var string
     *
     * @ORM\Column(name="provincia", type="string", length=100, nullable=true)
     */
    private $provincia;

    /**
     * @var string
     *
     * @ORM\Column(name="cp", type="string", length=20, nullable=true)
     */
    private $cp;

    /**
     * @var string
     *
     * @ORM\Column(name="tlf", type="string", length=20, nullable=false)
     */
    private $tlf;

    /**
     * @var string
     *
     * @ORM\Column(name="fax", type="string", length=20, nullable=false)
     */
    private $fax;

    /**
     * @var string
     *
     * @ORM\Column(name="cif", type="string", length=30, nullable=false)
     */
    private $cif;

    /**
     * @var string
     *
     * @ORM\Column(name="contacto", type="string", length=150, nullable=false)
     */
    private $contacto;

    /**
     * @var string
     *
     * @ORM\Column(name="cargo", type="string", length=150, nullable=false)
     */
    private $cargo;

    /**
     * @var DateTime
     *
     * @ORM\Column(name="fecha_exp", type="datetime", nullable=true)
     */
    private $fechaExp;

    /**
     * @var string
     *
     * @ORM\Column(name="user", type="string", length=50, nullable=false)
     */
    private $user;

    /**
     * @var string
     *
     * @ORM\Column(name="psw", type="string", length=50, nullable=false)
     */
    private $psw;

    /**
     * @var float
     *
     * @ORM\Column(name="tarifa", type="float", precision=10, scale=0, nullable=false)
     */
    private $tarifa;

    /**
     * @var integer
     *
     * @ORM\Column(name="tipo", type="integer", nullable=false)
     */
    private $tipo;

    /**
     * @var string
     *
     * @ORM\Column(name="observaciones", type="text", length=65535, nullable=true)
     */
    private $observaciones;

    /**
     * @var PreciosProductos[]
     *
     * @ORM\ManyToMany(targetEntity="PreciosProductos", inversedBy="usuarios")
     * @ORM\JoinTable(name="usuarios_productos")
     */
    protected $productos;

    /**
     * @var PreciosZonas[]
     *
     * @ORM\ManyToMany(targetEntity="PreciosZonas", inversedBy="usuarios")
     * @ORM\JoinTable(name="usuarios_zonas")
     */
    protected $zonas;

    /**
     * @var Asociaciones
     *
     * @ORM\ManyToOne(targetEntity="Asociaciones", inversedBy="usuarios")
     */
    private $asociacion;

    /**
     * @var MargenesProds[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="MargenesProds", mappedBy="user")
     */
    private $margenes;

    /**
     * @var Ips[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Ips", mappedBy="user")
     */
    private $ips;

    /**
     * @var Access[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Access", mappedBy="user")
     */
    private $accesos;

    /**
     * @var Formularios[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Formularios", mappedBy="cliente")
     */
    private $servicios;

    /**
     * @var Formularios[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Formularios", mappedBy="perito")
     */
    private $formularios;


    /**
     * Constructor
     */
    public function __construct()
    {
        $this->salt = md5(time().uniqid('', true));
        $this->active = false;
        $this->margenes = new ArrayCollection();
        $this->ips = new ArrayCollection();
        $this->accesos = new ArrayCollection();
        $this->servicios = new ArrayCollection();
        $this->formularios = new ArrayCollection();
        $this->provincia = new ArrayCollection();
        $this->zonas = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return User
     */
    public function setName(string $name): User
    {
        $this->name = ucwords(mb_strtolower($name));

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName(): ?string
    {
        return ucwords(mb_strtolower($this->name));
    }

    /**
     * Set email
     *
     * @param string $email
     * @return User
     */
    public function setEmail(string $email): User
    {
        $this->email = mb_strtolower($email);

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail(): ?string
    {
        return mb_strtolower($this->email);
    }

    /**
     * @return string
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * @param string $password
     * @return User
     */
    public function setPassword(string $password): User
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return string
     */
    public function getSalt(): ?string
    {
        return $this->salt;
    }

    /**
     * @param string $salt
     * @return User
     */
    public function setSalt(string $salt): User
    {
        $this->salt = $salt;

        return $this;
    }

    /**
     * @return bool
     */
    public function isActive(): ?bool
    {
        return $this->active;
    }

    /**
     * @param bool $active
     * @return User
     */
    public function setActive(bool $active): User
    {
        $this->active = $active;

        return $this;
    }

    /**
     * @return string
     */
    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    /**
     * @param string $avatar
     * @return User
     */
    public function setAvatar(string $avatar): User
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * @return DateTime
     */
    public function getLastAccess(): ?DateTime
    {
        return $this->lastAccess;
    }

    /**
     * @param DateTime $lastAccess
     * @return User
     */
    public function setLastAccess(DateTime $lastAccess): User
    {
        $this->lastAccess = $lastAccess;

        return $this;
    }

    /**
     * @return Role|null
     */
    public function getRole(): ?Role
    {
        return $this->role;
    }

    /**
     * @param Role $role
     * @return User
     */
    public function setRole(Role $role): User
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Get activeString
     *
     * @return string
     */
    public function isActiveString(): string
    {
        return StringsFunctions::getBooleanString($this->active);
    }

    /**
     * @return string
     */
    public function getRouteAvatar(): string
    {
        $avatar = ($this->avatar !== null && $this->avatar !== '') ? $this->avatar : 'avatar.png';

        return '/uploads/user/'.$avatar;
    }

    /**
     * @param UploadedFile $uploadedFile
     * @return User
     */
    public function setUploadedFile(UploadedFile $uploadedFile = null): User
    {
        $this->uploadedFile = $uploadedFile;

        return $this;
    }

    /**
     * @return UploadedFile
     */
    public function getUploadedFile(): ?UploadedFile
    {
        return $this->uploadedFile;
    }

    /**
     * @return array
     */
    public function getRoles(): array
    {
        $role = $this->getRole();

src/AppBundle/Form/UserType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'name',
                null,
                array(
                    'label' => 'user.name',
                )
            )
            ->add(
                'user',
                null,
                array(
                    'label' => 'Usuario',
                )
            )
            ->add(
                'email',
                null,
                array(
                    'label' => 'user.email',
                )
            )
            ->add(
                'password',
                RepeatedType::class,
                array(
                    'type' => PasswordType::class,
                    'invalid_message' => 'Passwords are not equal',
                    'options' => array(
                        'always_empty' => true,
                        'required' => 'required',
                    ),
                    'first_options' => array(
                        'label' => 'user.password',
                        'attr' => array(
                            'class' => 'text-input-border registro-user-pass',
                        ),
                    ),
                    'second_options' => array(
                        'label' => 'user.password_repeat',
                        'attr' => array(
                            'class' => 'text-input-border registro-user-pass',
                        ),
                    ),
                )
            )
            ->add(
                'uploadedFile',
                null,
                array(
                    'label' => 'user.avatar',
                )
            )
            ->add(
                'role',
                null,
                array(
                    'label' => 'user.role',
                )
            )
            ->add(
                'active',
                null,
                array(
                    'label' => 'user.active',
                )
            );
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => User::class,
            )
        );
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_user';
    }


}

src/AppBundle/Resources/views/user/edit.html.twig
{% extends '::intranet.html.twig' %}

{% block title %}{{ 'label.edit'|trans|capitalize }} {{ 'user.entity'|trans|capitalize }}{% endblock %}
{% block titleContent %}{{ 'label.edit'|trans|capitalize }} {{ 'user.entity'|trans|capitalize }}{% endblock %}

{% block breadcrumb %}
    <li>{{ 'menu.admin'|trans|capitalize }}</li>
    <li>{{ 'user.entity'|trans|capitalize }}</li>
    <li class="active">{{ 'label.edit'|trans|capitalize }}</li>
{% endblock %}

{% block contenido %}
    <div class="box box-solid">
        <div class="box-body text-right">
            <a class="btn btn-default" href="{{ path('app_user_show', { 'id': entity.id }) }}">
                {{ 'label.cancel'|trans|capitalize }}
            </a>
            <a class="btn btn-default" href="{{ path('app_user') }}">
                {{ 'label.list'|trans|capitalize }}
            </a>
            <a class="btn btn-warning" href="{{ path('app_user_change_password', { 'id': entity.id }) }}">
                {{ 'label.change_password'|trans|capitalize }}
            </a>
        </div>
    </div>

    {% include '::form_errors.html.twig' with {'form':edit_form} %}

    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ 'label.edit'|trans|capitalize }} {{ 'user.entity'|trans|capitalize }}</h3>
                </div>
                {{ form_start(edit_form) }}
                <div class="box-body">
                    {{ form_rest(edit_form) }}
                </div>
                <div class="box-footer">
                    <a class="btn btn-default"
                       href="{{ path('app_user_show', { 'id': entity.id }) }}">
                        {{ 'label.cancel'|trans|capitalize }}
                    </a>
                    <button type="submit"
                            class="btn btn-warning pull-right">{{ 'label.save'|trans|capitalize }}</button>
                </div>
                {{ form_end(edit_form) }}
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/user/edit_password.html.twig
{% extends '::intranet.html.twig' %}

{% block title %}{{ 'user.entity'|trans|capitalize }} {{ 'label.change_password'|trans|capitalize }}{% endblock %}
{% block titleContent %}{{ 'user.entity'|trans|capitalize }} {{ 'label.change_password'|trans|capitalize }}{% endblock %}

{% block breadcrumb %}
    <li>{{ 'menu.admin'|trans|capitalize }}</li>
    <li>{{ 'user.entity'|trans|capitalize }}</li>
    <li class="active">{{ 'label.change_password'|trans|capitalize }}</li>
{% endblock %}

{% block contenido %}
    <div class="box box-solid">
        <div class="box-body text-right">
            <a class="btn btn-default" href="{{ path('app_user_show', { 'id': entity.id }) }}">
                {{ 'label.cancel'|trans|capitalize }}
            </a>
            <a class="btn btn-default" href="{{ path('app_user') }}">
                {{ 'label.list'|trans|capitalize }}
            </a>
        </div>
    </div>

    {% include '::form_errors.html.twig' with {'form':edit_form} %}

    <div class="row">
        {{ form_start(edit_form) }}
        <div class="col-md-6">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ 'label.edit'|trans|capitalize }} {{ 'user.entity'|trans|capitalize }}</h3>
                </div>
                <div class="box-body">
                    <div class="col-md-12 form-group">
                        <div class="col-md-6">
                            {{ form_label(edit_form.password.first) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_widget(edit_form.password.first) }}
                            {{ form_errors(edit_form.password.first) }}
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <div class="col-md-6">
                            {{ form_label(edit_form.password.second) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_widget(edit_form.password.second) }}
                        </div>
                    </div>
                </div>
                <div class="box-footer text-right">
                    <span>
                        <a class="btn btn-default"
                           href="{{ path('app_user_show', { 'id': entity.id }) }}">{{ 'label.cancel'|trans|capitalize }}</a>
                    </span>
                    <button type="submit"
                            class="btn btn-warning pull-right">{{ 'label.save'|trans|capitalize }}</button>
                </div>
            </div>
        </div>
        {{ form_rest(edit_form) }}
        {{ form_end(edit_form) }}
    </div>
{% endblock %}

src/AppBundle/Resources/views/user/index.html.twig
{% extends '::datatable.html.twig' %}

{% block title %}{{ 'user.entity'|trans|capitalize }} {{ 'label.list'|trans|capitalize }}{% endblock %}
{% block titleContent %}{{ 'user.entity'|trans|capitalize }} {{ 'label.list'|trans|capitalize }}{% endblock %}

{% block breadcrumb %}
    <li>{{ 'menu.admin'|trans|capitalize }}</li>
    <li>{{ 'user.entity'|trans|capitalize }}</li>
    <li class="active">{{ 'label.list'|trans|capitalize }}</li>
{% endblock %}

{% block contenido %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid">
                <div class="box-body text-right">
                    <a class="btn btn-warning" href="{{ path('app_user_new') }}">{{ 'label.add'|trans|capitalize }}</a>
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="box">
                <div class="box-body">
                    {{ sg_datatables_render(datatable) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/user/new.html.twig
{% extends '::intranet.html.twig' %}

{% block title %}{{ 'label.add'|trans|capitalize }} {{ 'user.entity'|trans|capitalize }}{% endblock %}
{% block titleContent %}{{ 'label.add'|trans|capitalize }} {{ 'user.entity'|trans|capitalize }}{% endblock %}

{% block breadcrumb %}
    <li>{{ 'menu.admin'|trans|capitalize }}</li>
    <li>{{ 'user.entity'|trans|capitalize }}</li>
    <li class="active">{{ 'label.add'|trans|capitalize }}</li>
{% endblock %}

{% block contenido %}
    <div class="box box-solid">
        <div class="box-body text-right">
            <a class="btn btn-default" href="{{ path('app_user') }}">
                {{ 'label.list'|trans|capitalize }}
            </a>
        </div>
    </div>

    {% include '::form_errors.html.twig' %}

    <div class="row">
        {{ form_start(form) }}
        <div class="col-md-6">
            <div class="box">
                <div class="box-header with-border"><h3 class="box-title">{{ 'user.entity'|trans|capitalize }}</h3>
                </div>
                <div class="box-body">
                    <div class="col-md-12 form-group">
                        <div class="col-md-3">
                            {{ form_label(form.name) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_widget(form.name) }}
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <div class="col-md-3">
                            {{ form_label(form.user) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_widget(form.user) }}
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <div class="col-md-3">
                            {{ form_label(form.email) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_widget(form.email) }}
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <div class="col-md-3">
                            {{ form_label(form.password.first) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_widget(form.password.first) }}
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <div class="col-md-3">
                            {{ form_label(form.password.second) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_widget(form.password.second) }}
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <div class="col-md-3">
                            {{ form_label(form.role) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_widget(form.role) }}
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <div class="col-md-3">
                            {{ form_label(form.uploadedFile) }}
                        </div>
                        <div class="col-md-9">
                            {{ form_widget(form.uploadedFile) }}
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <div class="col-md-3">
                            {{ form_label(form.active) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_widget(form.active) }}
                        </div>
                    </div>
                </div>
                <div class="box-footer text-right">
                    <span>
                        <a class="btn btn-default"
                           href="{{ path('app_user') }}">{{ 'label.cancel'|trans|capitalize }}</a>
                    </span>
                    <button type="submit"
                            class="btn btn-warning pull-right">{{ 'label.save'|trans|capitalize }}</button>
                </div>
            </div>
        </div>
        {{ form_rest(form) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

src/AppBundle/Resources/views/user/show.html.twig
{% extends '::intranet.html.twig' %}

{% block title %}{{ 'user.entity'|trans|capitalize }}{% endblock %}
{% block titleContent %}{{ 'user.entity'|trans|capitalize }}{% endblock %}

{% block breadcrumb %}
    <li>{{ 'menu.admin'|trans|capitalize }}</li>
    <li>{{ 'user.entity'|trans|capitalize }}</li>
    <li class="active">{{ 'label.show'|trans|capitalize }}</li>
{% endblock %}

{% block contenido %}
    <div class="box box-solid">
        <div class="box-body text-right">
            {{ form_start(delete_form) }}
            {{ form_widget(delete_form.submit, { 'label': 'label.delete'|trans|capitalize }) }}
            <a class="btn btn-default" href="{{ path('app_user') }}">
                {{ 'label.list'|trans|capitalize }}
            </a>
            <a class="btn btn-warning" href="{{ path('app_user_change_password', { 'id': entity.id }) }}">
                {{ 'label.change_password'|trans|capitalize }}
            </a>
            <a class="btn btn-warning" href="{{ path('app_user_edit', { 'id': entity.id }) }}">
                {{ 'label.edit'|trans|capitalize }}
            </a>
            {{ form_rest(delete_form) }}
            {{ form_end(delete_form) }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ 'user.entity'|trans|capitalize }} {{ entity.id }}</h3>
                </div>
                <div class="box-body">
                    <table class="table table-striped">
                        <tbody>
                        <tr>
                            <th>Id</th>
                            <td>{{ entity.id }}</td>
                        </tr>
                        <tr>
                            <th>{{ 'user.email'|trans|capitalize }}</th>
                            <td>{{ entity.email }}</td>
                        </tr>
                        <tr>
                            <th>{{ 'user.name'|trans|capitalize }}</th>
                            <td>{{ entity.name }}</td>
                        </tr>
                        <tr>
                            <th>{{ 'user.active'|trans|capitalize }}</th>
                            <td>{{ entity.active }}</td>
                        </tr>
                        <tr>
                            <th>{{ 'user.last_access'|trans|capitalize }}</th>
                            <td>{% if entity.lastAccess %}{{ entity.lastAccess|date('d/m/Y') }}{% endif %}</td>
                        </tr>
                        <tr>
                            <th>Fecha exp</th>
                            <td>{% if entity.fechaExp %}{{ entity.fechaExp|date('d/m/Y') }}{% endif %}</td>
                        </tr>
                        <tr>
                            <th>{{ 'user.avatar'|trans|capitalize }}</th>
                            <td>{% if entity.avatar %}<img src="{{ entity.routeAvatar }}" height="75" />{% endif %}</td>
                        </tr>
                        <tr>
                            <th>{{ 'user.role'|trans|capitalize }}</th>
                            <td>{{ entity.role }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Dirección y datos de contacto</h3>
                </div>
                <div class="box-body">
                    <table class="table table-striped">
                        <tbody>
                        <tr>
                            <th>Provincia</th>
                            <td>{{ entity.provincia }}</td>
                        </tr>
                        <tr>
                            <th>Población</th>
                            <td>{{ entity.poblacion }}</td>
                        </tr>
                        <tr>
                            <th>CP</th>
                            <td>{{ entity.cp }}</td>
                        </tr>
                        <tr>
                            <th>Calle</th>
                            <td>{{ entity.calle }}</td>
                        </tr>
                        <tr>
                            <th>Dirección</th>
                            <td>{{ entity.direccion }}</td>
                        </tr>
                        <tr>
                            <th>Teléfono</th>
                            <td>{{ entity.tlf }}</td>
                        </tr>
                        <tr>
                            <th>Fax</th>
                            <td>{{ entity.fax }}</td>
                        </tr>
                        <tr>
                            <th>Contacto</th>
                            <td>{{ entity.contacto }}</td>
                        </tr>
                        <tr>
                            <th>Cargo</th>
                            <td>{{ entity.cargo }}</td>
                        </tr>
                        <tr>
                            <th>Asociación</th>
                            <td>{{ entity.asociacion }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}